# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:
    DepaOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            DepaBlockchainConsortium:
                Organizations:
                    - *PHRBlox
                    - *BPK
                    - *Pensook
    DepaChannel:
        Consortium: DepaBlockchainConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *PHRBlox
                - *BPK
                - *Pensook

Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/ehrblox.com/msp

    - &PHRBlox
        Name: PHRBloxMSP
        ID: PHRBloxMSP
        MSPDir: crypto-config/peerOrganizations/phr.ehrblox.com/msp
        AnchorPeers:
            - Host: peer0.phr.ehrblox.com
              Port: 7051

    - &BPK
        Name: BPKMSP
        ID: BPKMSP
        MSPDir: crypto-config/peerOrganizations/bpk.ehrblox.com/msp
        AnchorPeers:
            - Host: peer0.bpk.ehrblox.com
              Port: 7051

    - &Pensook
        Name: PensookMSP
        ID: PensookMSP
        MSPDir: crypto-config/peerOrganizations/pensook.ehrblox.com/msp
        AnchorPeers:
            - Host: peer0.pensook.ehrblox.com
              Port: 7051

Orderer: &OrdererDefaults
    OrdererType: solo

    Addresses:
        - orderer.ehrblox.com:7050

    BatchTimeout: 2s

    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Organizations:

Application: &ApplicationDefaults

    Organizations:
