# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:
  - Name: Orderer
    Domain: ehrblox.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: PHRBlox
    Domain: phr.ehrblox.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: BPK
    Domain: bpk.ehrblox.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Pensook
    Domain: pensook.ehrblox.com
    Template:
      Count: 1
    Users:
      Count: 1