# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  depanetwork:
services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.phr.ehrblox.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.phr.ehrblox.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/8bea8e8de5448717c57b996057c07d9c7c6ec2cfe55c6d8224d1be0b2d129206_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.phr.ehrblox.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/8bea8e8de5448717c57b996057c07d9c7c6ec2cfe55c6d8224d1be0b2d129206_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/phr.ehrblox.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - /var/hyperledger/ca0:/etc/hyperledger/fabric-ca-server
    container_name: ca_peer_phr
    networks:
      - depanetwork

  orderer.ehrblox.com:
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.ehrblox.com
    container_name: orderer.ehrblox.com
    networks:
      - depanetwork

  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=couchdb0_usr
      - COUCHDB_PASSWORD=couchdb0_pwd
    ports:
      - "5984:5984"
    volumes:
      - /var/hyperledger/couchdb0:/opt/couchdb/data
    networks:
      - depanetwork

  peer0.phr.ehrblox.com:
    container_name: peer0.phr.ehrblox.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.phr.ehrblox.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb0_usr
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchdb0_pwd
    depends_on:
      - couchdb0
      - orderer.ehrblox.com
    networks:
      - depanetwork

  mongo0:
    container_name: mongo0
    image: mongo
    volumes:
      - /var/hyperledger/mongo:/data
    ports:
      - "27017:27017"
    networks:
      - depanetwork

  rest0:
    container_name: rest0
    image: depa/blockchain-composer-rest-server
    volumes:
      - /home/imed/.composer/:/home/composer/.composer/
    environment:
      - COMPOSER_CARD=admin@my-network
      - COMPOSER_NAMESPACES=required
      - COMPOSER_AUTHENTICATION=true
      - COMPOSER_MULTIUSER=true
      - 'COMPOSER_PROVIDERS={"github": {"provider": "github", "module": "passport-github", "clientID": "cd9c1c736cafe3080972", "clientSecret": "de63d112587d11ffaeb170aaa8dfd7071786ccd4", "authPath": "/auth/github", "callbackURL": "/auth/github/callback", "successRedirect": "/", "failureRedirect": "/"}}'
      - 'COMPOSER_DATASOURCES={ "db": { "name": "db", "connector": "mongodb", "host": "mongo0" } }'
    ports:
      - "3000:3000"
    depends_on:
      - mongo0
    networks:
      - depanetwork