# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  depanetwork:
services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-phr
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.phr.ehrblox.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.phr.ehrblox.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/phr.ehrblox.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peer_phr
    networks:
      - depanetwork

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bpk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bpk.ehrblox.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.bpk.ehrblox.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/bpk.ehrblox.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peer_bpk
    networks:
      - depanetwork

  ca2:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-pensook
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.pensook.ehrblox.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.pensook.ehrblox.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/pensook.ehrblox.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peer_pensook
    networks:
      - depanetwork

  orderer.ehrblox.com:
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.ehrblox.com
    container_name: orderer.ehrblox.com
    networks:
      - depanetwork

  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=couchdb0_usr
      - COUCHDB_PASSWORD=couchdb0_pwd
    ports:
      - "5984:5984"
    networks:
      - depanetwork

  peer0.phr.ehrblox.com:
    container_name: peer0.phr.ehrblox.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.phr.ehrblox.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb0_usr
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchdb0_pwd
    depends_on:
      - couchdb0
    networks:
      - depanetwork

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=couchdb1_usr
      - COUCHDB_PASSWORD=couchdb1_pwd
    ports:
      - "6984:5984"
    networks:
      - depanetwork

  peer0.bpk.ehrblox.com:
    container_name: peer0.bpk.ehrblox.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.bpk.ehrblox.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb1_usr
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchdb1_pwd
    depends_on:
      - couchdb1
    networks:
      - depanetwork

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=couchdb2_usr
      - COUCHDB_PASSWORD=couchdb2_pwd
    ports:
      - "7984:5984"
    networks:
      - depanetwork

  peer0.pensook.ehrblox.com:
    container_name: peer0.pensook.ehrblox.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.pensook.ehrblox.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb2_usr
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchdb2_pwd
    depends_on:
      - couchdb2
    networks:
      - depanetwork