# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.ehrblox.com:
    container_name: orderer.ehrblox.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/ehrblox.com/orderers/orderer.ehrblox.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/ehrblox.com/orderers/orderer.ehrblox.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  peer0.phr.ehrblox.com:
    container_name: peer0.phr.ehrblox.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.phr.ehrblox.com
      - CORE_PEER_ADDRESS=peer0.phr.ehrblox.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.phr.ehrblox.com:7051
      - CORE_PEER_LOCALMSPID=PHRBloxMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../configtx.yaml:/etc/hyperledger/configtx.yaml
        - ../channel-artifacts/channel.tx:/var/hyperledger/channel-artifacts/channel.tx
        - ../channel-artifacts/PHRBloxMSPanchors.tx:/var/hyperledger/channel-artifacts/PHRBloxMSPanchors.tx
        - ../crypto-config/ordererOrganizations/ehrblox.com/orderers/orderer.ehrblox.com/msp/tlscacerts/tlsca.ehrblox.com-cert.pem:/var/hyperledger/crypto-config/ordererOrganizations/ehrblox.com/orderers/orderer.ehrblox.com/msp/tlscacerts/tlsca.ehrblox.com-cert.pem
        - ../crypto-config/peerOrganizations/phr.ehrblox.com/peers/peer0.phr.ehrblox.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/phr.ehrblox.com/peers/peer0.phr.ehrblox.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053

  peer0.bpk.ehrblox.com:
    container_name: peer0.bpk.ehrblox.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.bpk.ehrblox.com
      - CORE_PEER_ADDRESS=peer0.bpk.ehrblox.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bpk.ehrblox.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.phr.ehrblox.com:7051
      - CORE_PEER_LOCALMSPID=BPKMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../configtx.yaml:/etc/hyperledger/configtx.yaml
        - ../channel-artifacts/channel.tx:/var/hyperledger/channel-artifacts/channel.tx
        - ../channel-artifacts/BPKMSPanchors.tx:/var/hyperledger/channel-artifacts/BPKMSPanchors.tx
        - ../crypto-config/ordererOrganizations/ehrblox.com/orderers/orderer.ehrblox.com/msp/tlscacerts/tlsca.ehrblox.com-cert.pem:/var/hyperledger/crypto-config/ordererOrganizations/ehrblox.com/orderers/orderer.ehrblox.com/msp/tlscacerts/tlsca.ehrblox.com-cert.pem
        - ../crypto-config/peerOrganizations/bpk.ehrblox.com/peers/peer0.bpk.ehrblox.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/bpk.ehrblox.com/peers/peer0.bpk.ehrblox.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - 7051:7051
      - 7053:7053

  peer0.pensook.ehrblox.com:
    container_name: peer0.pensook.ehrblox.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.pensook.ehrblox.com
      - CORE_PEER_ADDRESS=peer0.pensook.ehrblox.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pensook.ehrblox.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pensook.ehrblox.com:7051
      - CORE_PEER_LOCALMSPID=PensookMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../configtx.yaml:/etc/hyperledger/configtx.yaml
        - ../channel-artifacts/channel.tx:/var/hyperledger/channel-artifacts/channel.tx
        - ../channel-artifacts/PensookMSPanchors.tx:/var/hyperledger/channel-artifacts/PensookMSPanchors.tx
        - ../crypto-config/ordererOrganizations/ehrblox.com/orderers/orderer.ehrblox.com/msp/tlscacerts/tlsca.ehrblox.com-cert.pem:/var/hyperledger/crypto-config/ordererOrganizations/ehrblox.com/orderers/orderer.ehrblox.com/msp/tlscacerts/tlsca.ehrblox.com-cert.pem
        - ../crypto-config/peerOrganizations/pensook.ehrblox.com/peers/peer0.pensook.ehrblox.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/pensook.ehrblox.com/peers/peer0.pensook.ehrblox.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053